[project]
name = "veratemple"
version = "0.1.0"
description = "An environment agnostic, agent composition framework."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fast-agent-mcp>=0.2.30",
]