[project]
name = "veratemple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fast-agent-mcp @ file:///${PROJECT_ROOT}/ext/fast-agent"
]
