[project]
name = "veratemple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fast-agent-mcp"
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
fast-agent-mpc = { path = "./ext/fast-agent" }